-- ================================================================
-- final_schema.sql  —  FaceZ HRMS  ·  FINAL flattened schema (V1 → V30)
-- ================================================================
-- Single, clean DDL for the CURRENT database state. Generated by
-- pg_dump (schema-only) from a fresh apply of all migrations, so
-- every table is one self-contained CREATE — no ALTER history.
-- USAGE : psql -U hrmsuser -d HRMS -f final_schema.sql
-- ================================================================
--
-- PostgreSQL database dump
--

\restrict Zn9Xc2ZT0TBvW4y8MRgfxMroDjkivJQt21lejUh9c6goKvdbpevr3BIgnoMWg3i

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.work_day DROP CONSTRAINT IF EXISTS fk_workday_employee;
ALTER TABLE IF EXISTS ONLY public.user_account DROP CONSTRAINT IF EXISTS fk_user_account_employee;
ALTER TABLE IF EXISTS ONLY public.timesheet DROP CONSTRAINT IF EXISTS fk_timesheet_employee;
ALTER TABLE IF EXISTS ONLY public.tax_dependent DROP CONSTRAINT IF EXISTS fk_tax_dependent_employee;
ALTER TABLE IF EXISTS ONLY public.salary_grade_step DROP CONSTRAINT IF EXISTS fk_salary_grade_step_grade;
ALTER TABLE IF EXISTS ONLY public.salary_grade DROP CONSTRAINT IF EXISTS fk_salary_grade_config;
ALTER TABLE IF EXISTS ONLY public.pit_bracket DROP CONSTRAINT IF EXISTS fk_pit_bracket_config;
ALTER TABLE IF EXISTS ONLY public.payroll DROP CONSTRAINT IF EXISTS fk_payroll_employee;
ALTER TABLE IF EXISTS ONLY public.ot_request DROP CONSTRAINT IF EXISTS fk_ot_request_plan;
ALTER TABLE IF EXISTS ONLY public.ot_request DROP CONSTRAINT IF EXISTS fk_ot_request_employee;
ALTER TABLE IF EXISTS ONLY public.ot_plan_employee DROP CONSTRAINT IF EXISTS fk_ope_plan;
ALTER TABLE IF EXISTS ONLY public.ot_plan_employee DROP CONSTRAINT IF EXISTS fk_ope_employee;
ALTER TABLE IF EXISTS ONLY public.notification DROP CONSTRAINT IF EXISTS fk_notification_employee;
ALTER TABLE IF EXISTS ONLY public.leave_request DROP CONSTRAINT IF EXISTS fk_leave_request_employee;
ALTER TABLE IF EXISTS ONLY public.leave_balance DROP CONSTRAINT IF EXISTS fk_leave_balance_employee;
ALTER TABLE IF EXISTS ONLY public.kpi1_rating DROP CONSTRAINT IF EXISTS fk_kpi1_employee;
ALTER TABLE IF EXISTS ONLY public.japanese_allowance_level DROP CONSTRAINT IF EXISTS fk_jp_allowance_config;
ALTER TABLE IF EXISTS ONLY public.insurance_eligible_contract_type DROP CONSTRAINT IF EXISTS fk_ins_eligible_config;
ALTER TABLE IF EXISTS ONLY public.employee_info DROP CONSTRAINT IF EXISTS fk_employee_department;
ALTER TABLE IF EXISTS ONLY public.department DROP CONSTRAINT IF EXISTS fk_department_parent;
ALTER TABLE IF EXISTS ONLY public.department DROP CONSTRAINT IF EXISTS fk_department_manager;
ALTER TABLE IF EXISTS ONLY public.contract DROP CONSTRAINT IF EXISTS fk_contract_employee;
ALTER TABLE IF EXISTS ONLY public.check_in_log DROP CONSTRAINT IF EXISTS fk_checkin_log_employee;
ALTER TABLE IF EXISTS ONLY public.check_in_log DROP CONSTRAINT IF EXISTS fk_checkin_log_device;
ALTER TABLE IF EXISTS ONLY public.attendance DROP CONSTRAINT IF EXISTS fk_attendance_employee;
ALTER TABLE IF EXISTS ONLY public.attendance_adjustment DROP CONSTRAINT IF EXISTS fk_attadj_employee;
ALTER TABLE IF EXISTS ONLY public.api_key DROP CONSTRAINT IF EXISTS fk_api_key_device;
ALTER TABLE IF EXISTS ONLY public.allowance_rule_value DROP CONSTRAINT IF EXISTS fk_allowance_rule_config;
ALTER TABLE IF EXISTS ONLY public.allowance_level DROP CONSTRAINT IF EXISTS fk_allowance_level_config;
DROP INDEX IF EXISTS public.uk_salary_grade_published_eff;
DROP INDEX IF EXISTS public.uk_pit_published_eff;
DROP INDEX IF EXISTS public.uk_insurance_published_eff;
DROP INDEX IF EXISTS public.uk_allowance_published_eff;
DROP INDEX IF EXISTS public.idx_workday_locked;
DROP INDEX IF EXISTS public.idx_workday_employee_date;
DROP INDEX IF EXISTS public.idx_workday_date_source;
DROP INDEX IF EXISTS public.idx_timesheet_period;
DROP INDEX IF EXISTS public.idx_tax_dependent_employee;
DROP INDEX IF EXISTS public.idx_syscfg_type_version;
DROP INDEX IF EXISTS public.idx_syscfg_type_active;
DROP INDEX IF EXISTS public.idx_salary_grade_config_lookup;
DROP INDEX IF EXISTS public.idx_public_holiday_year;
DROP INDEX IF EXISTS public.idx_public_holiday_date;
DROP INDEX IF EXISTS public.idx_pit_config_lookup;
DROP INDEX IF EXISTS public.idx_payroll_run_id;
DROP INDEX IF EXISTS public.idx_ot_plan_status;
DROP INDEX IF EXISTS public.idx_ot_plan_date;
DROP INDEX IF EXISTS public.idx_ope_plan;
DROP INDEX IF EXISTS public.idx_ope_employee;
DROP INDEX IF EXISTS public.idx_notification_employee;
DROP INDEX IF EXISTS public.idx_leave_balance_employee;
DROP INDEX IF EXISTS public.idx_kpi1_period;
DROP INDEX IF EXISTS public.idx_insurance_config_lookup;
DROP INDEX IF EXISTS public.idx_contract_employee_current;
DROP INDEX IF EXISTS public.idx_attadj_status;
DROP INDEX IF EXISTS public.idx_attadj_employee;
DROP INDEX IF EXISTS public.idx_api_key_hash;
DROP INDEX IF EXISTS public.idx_api_key_device;
DROP INDEX IF EXISTS public.idx_allowance_config_lookup;
ALTER TABLE IF EXISTS ONLY public.work_day DROP CONSTRAINT IF EXISTS work_day_pkey;
ALTER TABLE IF EXISTS ONLY public.user_account DROP CONSTRAINT IF EXISTS user_account_pkey;
ALTER TABLE IF EXISTS ONLY public.work_day DROP CONSTRAINT IF EXISTS uk_workday_employee_date;
ALTER TABLE IF EXISTS ONLY public.user_account DROP CONSTRAINT IF EXISTS uk_user_account_username;
ALTER TABLE IF EXISTS ONLY public.timesheet DROP CONSTRAINT IF EXISTS uk_timesheet_employee_period;
ALTER TABLE IF EXISTS ONLY public.salary_grade_step DROP CONSTRAINT IF EXISTS uk_salary_grade_step;
ALTER TABLE IF EXISTS ONLY public.salary_grade DROP CONSTRAINT IF EXISTS uk_salary_grade_code;
ALTER TABLE IF EXISTS ONLY public.pit_bracket DROP CONSTRAINT IF EXISTS uk_pit_bracket_seq;
ALTER TABLE IF EXISTS ONLY public.attendance_period_close DROP CONSTRAINT IF EXISTS uk_period_close_year_month;
ALTER TABLE IF EXISTS ONLY public.payroll_run DROP CONSTRAINT IF EXISTS uk_payroll_run_period;
ALTER TABLE IF EXISTS ONLY public.payroll DROP CONSTRAINT IF EXISTS uk_payroll_employee_period;
ALTER TABLE IF EXISTS ONLY public.ot_plan_employee DROP CONSTRAINT IF EXISTS uk_ot_plan_employee;
ALTER TABLE IF EXISTS ONLY public.leave_balance DROP CONSTRAINT IF EXISTS uk_leave_balance_employee_year_type;
ALTER TABLE IF EXISTS ONLY public.kpi1_rating DROP CONSTRAINT IF EXISTS uk_kpi1_employee_period;
ALTER TABLE IF EXISTS ONLY public.japanese_allowance_level DROP CONSTRAINT IF EXISTS uk_jp_allowance_level;
ALTER TABLE IF EXISTS ONLY public.insurance_eligible_contract_type DROP CONSTRAINT IF EXISTS uk_ins_eligible;
ALTER TABLE IF EXISTS ONLY public.employee_info DROP CONSTRAINT IF EXISTS uk_employee_tax_code;
ALTER TABLE IF EXISTS ONLY public.employee_info DROP CONSTRAINT IF EXISTS uk_employee_si_code;
ALTER TABLE IF EXISTS ONLY public.employee_info DROP CONSTRAINT IF EXISTS uk_employee_national_id;
ALTER TABLE IF EXISTS ONLY public.department DROP CONSTRAINT IF EXISTS uk_department_manager;
ALTER TABLE IF EXISTS ONLY public.attendance DROP CONSTRAINT IF EXISTS uk_attendance_employee_date;
ALTER TABLE IF EXISTS ONLY public.allowance_rule_value DROP CONSTRAINT IF EXISTS uk_allowance_rule;
ALTER TABLE IF EXISTS ONLY public.allowance_level DROP CONSTRAINT IF EXISTS uk_allowance_level;
ALTER TABLE IF EXISTS ONLY public.timesheet DROP CONSTRAINT IF EXISTS timesheet_pkey;
ALTER TABLE IF EXISTS ONLY public.tax_dependent DROP CONSTRAINT IF EXISTS tax_dependent_pkey;
ALTER TABLE IF EXISTS ONLY public.system_config DROP CONSTRAINT IF EXISTS system_config_pkey;
ALTER TABLE IF EXISTS ONLY public.salary_grade_step DROP CONSTRAINT IF EXISTS salary_grade_step_pkey;
ALTER TABLE IF EXISTS ONLY public.salary_grade DROP CONSTRAINT IF EXISTS salary_grade_pkey;
ALTER TABLE IF EXISTS ONLY public.salary_grade_config DROP CONSTRAINT IF EXISTS salary_grade_config_pkey;
ALTER TABLE IF EXISTS ONLY public.public_holiday DROP CONSTRAINT IF EXISTS public_holiday_pkey;
ALTER TABLE IF EXISTS ONLY public.benefit DROP CONSTRAINT IF EXISTS pk_benefit;
ALTER TABLE IF EXISTS ONLY public.pit_config DROP CONSTRAINT IF EXISTS pit_config_pkey;
ALTER TABLE IF EXISTS ONLY public.pit_bracket DROP CONSTRAINT IF EXISTS pit_bracket_pkey;
ALTER TABLE IF EXISTS ONLY public.payroll_run DROP CONSTRAINT IF EXISTS payroll_run_pkey;
ALTER TABLE IF EXISTS ONLY public.payroll DROP CONSTRAINT IF EXISTS payroll_pkey;
ALTER TABLE IF EXISTS ONLY public.ot_request DROP CONSTRAINT IF EXISTS ot_request_pkey;
ALTER TABLE IF EXISTS ONLY public.ot_plan DROP CONSTRAINT IF EXISTS ot_plan_pkey;
ALTER TABLE IF EXISTS ONLY public.ot_plan_employee DROP CONSTRAINT IF EXISTS ot_plan_employee_pkey;
ALTER TABLE IF EXISTS ONLY public.notification DROP CONSTRAINT IF EXISTS notification_pkey;
ALTER TABLE IF EXISTS ONLY public.leave_request DROP CONSTRAINT IF EXISTS leave_request_pkey;
ALTER TABLE IF EXISTS ONLY public.leave_balance DROP CONSTRAINT IF EXISTS leave_balance_pkey;
ALTER TABLE IF EXISTS ONLY public.kpi1_rating DROP CONSTRAINT IF EXISTS kpi1_rating_pkey;
ALTER TABLE IF EXISTS ONLY public.japanese_allowance_level DROP CONSTRAINT IF EXISTS japanese_allowance_level_pkey;
ALTER TABLE IF EXISTS ONLY public.insurance_eligible_contract_type DROP CONSTRAINT IF EXISTS insurance_eligible_contract_type_pkey;
ALTER TABLE IF EXISTS ONLY public.insurance_config DROP CONSTRAINT IF EXISTS insurance_config_pkey;
ALTER TABLE IF EXISTS ONLY public.employee_info DROP CONSTRAINT IF EXISTS employee_info_pkey;
ALTER TABLE IF EXISTS ONLY public.device DROP CONSTRAINT IF EXISTS device_pkey;
ALTER TABLE IF EXISTS ONLY public.department DROP CONSTRAINT IF EXISTS department_pkey;
ALTER TABLE IF EXISTS ONLY public.contract DROP CONSTRAINT IF EXISTS contract_pkey;
ALTER TABLE IF EXISTS ONLY public.check_in_log DROP CONSTRAINT IF EXISTS check_in_log_pkey;
ALTER TABLE IF EXISTS ONLY public.attendance DROP CONSTRAINT IF EXISTS attendance_pkey;
ALTER TABLE IF EXISTS ONLY public.attendance_period_close DROP CONSTRAINT IF EXISTS attendance_period_close_pkey;
ALTER TABLE IF EXISTS ONLY public.attendance_adjustment DROP CONSTRAINT IF EXISTS attendance_adjustment_pkey;
ALTER TABLE IF EXISTS ONLY public.api_key DROP CONSTRAINT IF EXISTS api_key_pkey;
ALTER TABLE IF EXISTS ONLY public.allowance_rule_value DROP CONSTRAINT IF EXISTS allowance_rule_value_pkey;
ALTER TABLE IF EXISTS ONLY public.allowance_level DROP CONSTRAINT IF EXISTS allowance_level_pkey;
ALTER TABLE IF EXISTS ONLY public.allowance_config DROP CONSTRAINT IF EXISTS allowance_config_pkey;
DROP TABLE IF EXISTS public.work_day;
DROP TABLE IF EXISTS public.user_account;
DROP TABLE IF EXISTS public.timesheet;
DROP TABLE IF EXISTS public.tax_dependent;
DROP TABLE IF EXISTS public.system_config;
DROP TABLE IF EXISTS public.salary_grade_step;
DROP TABLE IF EXISTS public.salary_grade_config;
DROP TABLE IF EXISTS public.salary_grade;
DROP TABLE IF EXISTS public.public_holiday;
DROP TABLE IF EXISTS public.pit_config;
DROP TABLE IF EXISTS public.pit_bracket;
DROP TABLE IF EXISTS public.payroll_run;
DROP TABLE IF EXISTS public.payroll;
DROP TABLE IF EXISTS public.ot_plan_employee;
DROP TABLE IF EXISTS public.ot_plan;
DROP VIEW IF EXISTS public.ot_monthly_summary;
DROP TABLE IF EXISTS public.ot_request;
DROP TABLE IF EXISTS public.notification;
DROP TABLE IF EXISTS public.leave_request;
DROP TABLE IF EXISTS public.leave_balance;
DROP TABLE IF EXISTS public.kpi1_rating;
DROP TABLE IF EXISTS public.japanese_allowance_level;
DROP TABLE IF EXISTS public.insurance_eligible_contract_type;
DROP TABLE IF EXISTS public.insurance_config;
DROP TABLE IF EXISTS public.employee_info;
DROP TABLE IF EXISTS public.device;
DROP TABLE IF EXISTS public.department;
DROP TABLE IF EXISTS public.contract;
DROP TABLE IF EXISTS public.check_in_log;
DROP TABLE IF EXISTS public.benefit;
DROP TABLE IF EXISTS public.attendance_period_close;
DROP TABLE IF EXISTS public.attendance_adjustment;
DROP TABLE IF EXISTS public.attendance;
DROP TABLE IF EXISTS public.api_key;
DROP TABLE IF EXISTS public.allowance_rule_value;
DROP TABLE IF EXISTS public.allowance_level;
DROP TABLE IF EXISTS public.allowance_config;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: allowance_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.allowance_config (
    id character varying(64) NOT NULL,
    effective_from date NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    legal_basis character varying(300),
    living_prorated boolean DEFAULT true NOT NULL,
    japanese_prorated boolean DEFAULT false NOT NULL,
    japanese_min_contract_months integer,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: allowance_level; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.allowance_level (
    id character varying(64) NOT NULL,
    config_id character varying(64) NOT NULL,
    level_key character varying(40) NOT NULL,
    meal bigint DEFAULT 0 NOT NULL,
    phone bigint DEFAULT 0 NOT NULL,
    transport bigint DEFAULT 0 NOT NULL,
    housing bigint DEFAULT 0 NOT NULL
);


--
-- Name: allowance_rule_value; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.allowance_rule_value (
    id character varying(64) NOT NULL,
    config_id character varying(64) NOT NULL,
    kind character varying(40) NOT NULL,
    value character varying(60) NOT NULL
);


--
-- Name: api_key; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_key (
    id character varying(64) NOT NULL,
    key_hash character varying(100) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    device_id character varying(255) NOT NULL,
    created_at timestamp without time zone,
    last_used_at timestamp without time zone
);


--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
    attendance_id character varying(255) NOT NULL,
    attendance_date date DEFAULT '2024-01-01'::date NOT NULL,
    check_in timestamp without time zone,
    check_out timestamp without time zone,
    late_hour numeric(38,2),
    working_hour numeric(38,2),
    paid_hour numeric(38,2),
    working_day numeric(38,2),
    paid_day numeric(38,2),
    violate boolean DEFAULT false NOT NULL,
    employee_id character varying(64),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: attendance_adjustment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_adjustment (
    id character varying(64) NOT NULL,
    employee_id character varying(64) NOT NULL,
    work_date date NOT NULL,
    requested_check_in timestamp without time zone,
    requested_check_out timestamp without time zone,
    reason character varying(500),
    status character varying(30) DEFAULT 'TO_APPROVE'::character varying NOT NULL,
    rejection_reason character varying(500),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: attendance_period_close; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_period_close (
    id character varying(64) NOT NULL,
    close_year integer NOT NULL,
    close_month integer NOT NULL,
    closed_by character varying(100),
    closed_at timestamp without time zone,
    notes character varying(500)
);


--
-- Name: benefit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.benefit (
    benefit_rank character varying(255) NOT NULL,
    employee_level character varying(255),
    housing_benefit character varying(255),
    meal_benefit character varying(255),
    vehicle_benefit character varying(255),
    phone_benefit character varying(255),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: check_in_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.check_in_log (
    log_id character varying(255) NOT NULL,
    log_time timestamp without time zone,
    log_type character varying(255),
    device_id character varying(255),
    employee_id character varying(64),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: contract; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contract (
    id character varying(255) NOT NULL,
    contract_type character varying(255),
    status character varying(255),
    start_date date,
    end_date date,
    effective_from date,
    effective_to date,
    current_contract boolean DEFAULT true NOT NULL,
    salary_rank character varying(255),
    base_salary bigint,
    insurance_base bigint,
    position_code character varying(10),
    salary_step integer,
    dependent_count integer,
    terms character varying(255),
    notes character varying(500),
    attachment bytea,
    employee_id character varying(64),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    document_key character varying(300)
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department (
    department_id character varying(255) NOT NULL,
    department_name character varying(255),
    manager_id character varying(64),
    parent_id character varying(255),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: device; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device (
    device_id character varying(255) NOT NULL,
    device_name character varying(255),
    log_type character varying(255),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    location character varying(255),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: employee_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_info (
    employee_id character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    role character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    email character varying(150),
    phone_number character varying(50),
    address character varying(500),
    date_of_joining date,
    emergency_contact character varying(200),
    profile_picture oid,
    profile_picture_url character varying(500),
    national_id character varying(20),
    national_id_issue_date date,
    national_id_issue_place character varying(200),
    tax_code character varying(20),
    social_insurance_code character varying(20),
    bank_account_number character varying(30),
    bank_name character varying(100),
    bank_branch character varying(200),
    date_of_birth date,
    gender character varying(10),
    hometown character varying(200),
    department_id character varying(255),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: insurance_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insurance_config (
    id character varying(64) NOT NULL,
    effective_from date NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    legal_basis character varying(300),
    government_base_salary bigint,
    insurance_ceiling bigint,
    statutory_min_wage bigint,
    ee_bhxh numeric(6,5) NOT NULL,
    ee_bhyt numeric(6,5) NOT NULL,
    ee_bhtn numeric(6,5) NOT NULL,
    er_bhxh_pension numeric(6,5) NOT NULL,
    er_bhxh_sickness_maternity numeric(6,5) NOT NULL,
    er_bhxh_accident numeric(6,5) NOT NULL,
    er_bhyt numeric(6,5) NOT NULL,
    er_bhtn numeric(6,5) NOT NULL,
    probation_exempt boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    CONSTRAINT chk_ins_ee_bhtn CHECK (((ee_bhtn >= (0)::numeric) AND (ee_bhtn <= (1)::numeric))),
    CONSTRAINT chk_ins_ee_bhxh CHECK (((ee_bhxh >= (0)::numeric) AND (ee_bhxh <= (1)::numeric))),
    CONSTRAINT chk_ins_ee_bhyt CHECK (((ee_bhyt >= (0)::numeric) AND (ee_bhyt <= (1)::numeric))),
    CONSTRAINT chk_ins_er_accident CHECK (((er_bhxh_accident >= (0)::numeric) AND (er_bhxh_accident <= (1)::numeric))),
    CONSTRAINT chk_ins_er_bhtn CHECK (((er_bhtn >= (0)::numeric) AND (er_bhtn <= (1)::numeric))),
    CONSTRAINT chk_ins_er_bhyt CHECK (((er_bhyt >= (0)::numeric) AND (er_bhyt <= (1)::numeric))),
    CONSTRAINT chk_ins_er_pension CHECK (((er_bhxh_pension >= (0)::numeric) AND (er_bhxh_pension <= (1)::numeric))),
    CONSTRAINT chk_ins_er_sickness CHECK (((er_bhxh_sickness_maternity >= (0)::numeric) AND (er_bhxh_sickness_maternity <= (1)::numeric)))
);


--
-- Name: insurance_eligible_contract_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.insurance_eligible_contract_type (
    id character varying(64) NOT NULL,
    config_id character varying(64) NOT NULL,
    contract_type character varying(30) NOT NULL
);


--
-- Name: japanese_allowance_level; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.japanese_allowance_level (
    id character varying(64) NOT NULL,
    config_id character varying(64) NOT NULL,
    jlpt_level character varying(10) NOT NULL,
    amount bigint DEFAULT 0 NOT NULL
);


--
-- Name: kpi1_rating; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kpi1_rating (
    id character varying(64) NOT NULL,
    employee_id character varying(64) NOT NULL,
    kpi_year integer NOT NULL,
    kpi_month integer NOT NULL,
    rating character varying(2) NOT NULL,
    evaluator_id character varying(64),
    note character varying(300),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: leave_balance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leave_balance (
    id character varying(64) NOT NULL,
    leave_year integer NOT NULL,
    leave_type character varying(30) NOT NULL,
    entitlement_days numeric(10,2) DEFAULT 0 NOT NULL,
    carried_over_days numeric(10,2) DEFAULT 0 NOT NULL,
    pending_days numeric(10,2) DEFAULT 0 NOT NULL,
    used_days numeric(10,2) DEFAULT 0 NOT NULL,
    remaining_days numeric(10,2) DEFAULT 0 NOT NULL,
    carry_over_cap numeric(10,2) DEFAULT 5 NOT NULL,
    employee_id character varying(64) NOT NULL
);


--
-- Name: leave_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leave_request (
    leave_request_id character varying(255) NOT NULL,
    leave_type character varying(30) DEFAULT 'ANNUAL'::character varying NOT NULL,
    reason character varying(255),
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    duration_hours numeric(10,2),
    balance_deducted boolean DEFAULT false NOT NULL,
    status character varying(255),
    employee_id character varying(64),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id character varying(64) NOT NULL,
    title character varying(200) NOT NULL,
    message character varying(500) NOT NULL,
    type character varying(50) DEFAULT 'INFO'::character varying NOT NULL,
    read_flag boolean DEFAULT false NOT NULL,
    employee_id character varying(64) NOT NULL,
    created_at timestamp without time zone
);


--
-- Name: ot_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ot_request (
    ot_request_id character varying(255) NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(255),
    employee_id character varying(64),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    ot_plan_id character varying(64),
    coefficient double precision DEFAULT 1.5 NOT NULL
);


--
-- Name: ot_monthly_summary; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.ot_monthly_summary AS
 SELECT employee_id,
    (EXTRACT(year FROM start_time))::integer AS ot_year,
    (EXTRACT(month FROM start_time))::integer AS ot_month,
    sum((EXTRACT(epoch FROM (end_time - start_time)) / (60)::numeric)) AS approved_minutes
   FROM public.ot_request ot
  WHERE (((status)::text = 'APPROVED'::text) AND (delete_flag = false))
  GROUP BY employee_id, ((EXTRACT(year FROM start_time))::integer), ((EXTRACT(month FROM start_time))::integer);


--
-- Name: ot_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ot_plan (
    id character varying(64) NOT NULL,
    ot_date date NOT NULL,
    planned_start_time time without time zone,
    planned_end_time time without time zone,
    department_id character varying(255),
    reason character varying(500),
    status character varying(30) DEFAULT 'TO_APPROVE'::character varying NOT NULL,
    rejection_reason character varying(500),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: ot_plan_employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ot_plan_employee (
    id character varying(64) NOT NULL,
    ot_plan_id character varying(64) NOT NULL,
    employee_id character varying(64) NOT NULL
);


--
-- Name: payroll; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payroll (
    payroll_id character varying(64) NOT NULL,
    payroll_year integer NOT NULL,
    payroll_month integer NOT NULL,
    actual_working_days integer DEFAULT 0 NOT NULL,
    standard_working_days integer DEFAULT 0 NOT NULL,
    kpi1score double precision DEFAULT 1.0 NOT NULL,
    kpi2score double precision DEFAULT 1.0 NOT NULL,
    kpi_average double precision DEFAULT 1.0 NOT NULL,
    performance_salary bigint DEFAULT 0 NOT NULL,
    position_coefficient bigint DEFAULT 0 NOT NULL,
    living_allowance bigint DEFAULT 0 NOT NULL,
    language_allowance bigint DEFAULT 0 NOT NULL,
    odc_allowance bigint DEFAULT 0 NOT NULL,
    ot_pay bigint DEFAULT 0 NOT NULL,
    bonus bigint DEFAULT 0 NOT NULL,
    base_gross bigint DEFAULT 0 NOT NULL,
    total_gross bigint DEFAULT 0 NOT NULL,
    insurance_base bigint DEFAULT 0 NOT NULL,
    bhxh_employee bigint DEFAULT 0 NOT NULL,
    bhyt_employee bigint DEFAULT 0 NOT NULL,
    bhtn_employee bigint DEFAULT 0 NOT NULL,
    dependent_count integer DEFAULT 0 NOT NULL,
    taxable_income bigint DEFAULT 0 NOT NULL,
    pit bigint DEFAULT 0 NOT NULL,
    bhxh_employer bigint DEFAULT 0 NOT NULL,
    bhyt_employer bigint DEFAULT 0 NOT NULL,
    bhtn_employer bigint DEFAULT 0 NOT NULL,
    workplace_accident_insurance bigint DEFAULT 0 NOT NULL,
    total_employer_contributions bigint DEFAULT 0 NOT NULL,
    total_employment_cost bigint DEFAULT 0 NOT NULL,
    net_salary bigint DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    rejection_reason character varying(500),
    notes character varying(500),
    employee_id character varying(64) NOT NULL,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    payroll_run_id character varying(64),
    locked boolean DEFAULT false NOT NULL,
    ot_weekday_hours numeric(7,2) DEFAULT 0 NOT NULL,
    ot_weekend_hours numeric(7,2) DEFAULT 0 NOT NULL,
    ot_holiday_hours numeric(7,2) DEFAULT 0 NOT NULL,
    ot_night_hours numeric(7,2) DEFAULT 0 NOT NULL
);


--
-- Name: payroll_run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payroll_run (
    id character varying(64) NOT NULL,
    run_year integer NOT NULL,
    run_month integer NOT NULL,
    status character varying(20) NOT NULL,
    employee_count integer DEFAULT 0 NOT NULL,
    total_gross bigint DEFAULT 0 NOT NULL,
    total_net bigint DEFAULT 0 NOT NULL,
    submitted_by character varying(100),
    approved_by character varying(100),
    rejection_reason character varying(500),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: pit_bracket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pit_bracket (
    id character varying(64) NOT NULL,
    config_id character varying(64) NOT NULL,
    seq integer NOT NULL,
    income_from bigint NOT NULL,
    income_to bigint,
    rate numeric(6,5) NOT NULL,
    quick_deduction bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_pit_bracket_rate CHECK (((rate >= (0)::numeric) AND (rate <= (1)::numeric)))
);


--
-- Name: pit_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pit_config (
    id character varying(64) NOT NULL,
    effective_from date NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    legal_basis character varying(300),
    resolution character varying(300),
    personal_relief bigint NOT NULL,
    dependent_relief bigint NOT NULL,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: public_holiday; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_holiday (
    id character varying(64) NOT NULL,
    holiday_year integer NOT NULL,
    holiday_date date NOT NULL,
    name character varying(200) NOT NULL,
    compensatory_day date
);


--
-- Name: salary_grade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.salary_grade (
    id character varying(64) NOT NULL,
    config_id character varying(64) CONSTRAINT salary_grade_config_id_not_null1 NOT NULL,
    grade_code character varying(30) NOT NULL,
    title character varying(255),
    track character varying(30)
);


--
-- Name: salary_grade_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.salary_grade_config (
    id character varying(64) NOT NULL,
    effective_from date NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    legal_basis character varying(300),
    unit character varying(30) DEFAULT 'thousand_vnd'::character varying NOT NULL,
    minimum_wage_region_i integer,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: salary_grade_step; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.salary_grade_step (
    id character varying(64) NOT NULL,
    grade_id character varying(64) NOT NULL,
    step_no integer NOT NULL,
    amount_thousand_vnd bigint NOT NULL,
    CONSTRAINT chk_salary_grade_step_no CHECK (((step_no >= 1) AND (step_no <= 10)))
);


--
-- Name: system_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_config (
    id character varying(64) NOT NULL,
    config_type character varying(30) NOT NULL,
    version character varying(30) NOT NULL,
    effective_date date,
    legal_basis character varying(300),
    config_data jsonb NOT NULL,
    active boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: tax_dependent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax_dependent (
    id character varying(64) NOT NULL,
    full_name character varying(200) NOT NULL,
    national_id character varying(20),
    date_of_birth date,
    relationship character varying(100),
    registration_date date,
    active boolean DEFAULT true NOT NULL,
    employee_id character varying(64) NOT NULL
);


--
-- Name: timesheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.timesheet (
    id character varying(64) NOT NULL,
    employee_id character varying(64) NOT NULL,
    ts_year integer NOT NULL,
    ts_month integer NOT NULL,
    standard_working_days integer,
    actual_working_days numeric(10,2),
    holiday_leave_days numeric(10,2),
    annual_leave_days numeric(10,2),
    comp_leave_days numeric(10,2),
    bereavement_marriage_days numeric(10,2),
    insurance_leave_days numeric(10,2),
    unpaid_leave_days numeric(10,2),
    old_rate_paid_days numeric(10,2),
    new_rate_paid_days numeric(10,2),
    total_paid_days numeric(10,2),
    carry_over_prev_month numeric(10,2),
    business_go_out_days numeric(10,2),
    wfh_days numeric(10,2),
    unexplained_absence_days numeric(10,2),
    late_early_total_hours numeric(10,2),
    violation_to_comp numeric(10,2),
    violation_to_leave numeric(10,2),
    violation_to_unpaid numeric(10,2),
    unnotified_absence_count integer,
    under8h_count integer,
    attendance_request_errors integer,
    kpi2_deduction bigint,
    kpi2_index numeric(10,2),
    prev_month_violation_adjust numeric(10,2),
    notes character varying(1000),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    ot_hours numeric(10,2)
);


--
-- Name: user_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_account (
    employee_id character varying(64) NOT NULL,
    username character varying(255),
    password_hash character varying(100) NOT NULL,
    last_password_hash character varying(255),
    role character varying(30) NOT NULL,
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100),
    delete_flag boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: work_day; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_day (
    id character varying(64) NOT NULL,
    employee_id character varying(64) NOT NULL,
    work_date date NOT NULL,
    type character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    leave_type character varying(30),
    check_in timestamp without time zone,
    check_out timestamp without time zone,
    late_hour numeric(10,2) DEFAULT 0 NOT NULL,
    working_hour numeric(10,2) DEFAULT 0 NOT NULL,
    ot_minutes integer DEFAULT 0 NOT NULL,
    paid_day numeric(10,2) DEFAULT 0 NOT NULL,
    working_day numeric(10,2) DEFAULT 0 NOT NULL,
    violation boolean DEFAULT false NOT NULL,
    locked boolean DEFAULT false NOT NULL,
    attendance_id character varying(64),
    leave_request_id character varying(64),
    created_at timestamp without time zone,
    created_by character varying(100),
    updated_at timestamp without time zone,
    updated_by character varying(100)
);


--
-- Name: allowance_config allowance_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_config
    ADD CONSTRAINT allowance_config_pkey PRIMARY KEY (id);


--
-- Name: allowance_level allowance_level_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_level
    ADD CONSTRAINT allowance_level_pkey PRIMARY KEY (id);


--
-- Name: allowance_rule_value allowance_rule_value_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_rule_value
    ADD CONSTRAINT allowance_rule_value_pkey PRIMARY KEY (id);


--
-- Name: api_key api_key_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key
    ADD CONSTRAINT api_key_pkey PRIMARY KEY (id);


--
-- Name: attendance_adjustment attendance_adjustment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_adjustment
    ADD CONSTRAINT attendance_adjustment_pkey PRIMARY KEY (id);


--
-- Name: attendance_period_close attendance_period_close_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_period_close
    ADD CONSTRAINT attendance_period_close_pkey PRIMARY KEY (id);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id);


--
-- Name: check_in_log check_in_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.check_in_log
    ADD CONSTRAINT check_in_log_pkey PRIMARY KEY (log_id);


--
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (department_id);


--
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (device_id);


--
-- Name: employee_info employee_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_info
    ADD CONSTRAINT employee_info_pkey PRIMARY KEY (employee_id);


--
-- Name: insurance_config insurance_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insurance_config
    ADD CONSTRAINT insurance_config_pkey PRIMARY KEY (id);


--
-- Name: insurance_eligible_contract_type insurance_eligible_contract_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insurance_eligible_contract_type
    ADD CONSTRAINT insurance_eligible_contract_type_pkey PRIMARY KEY (id);


--
-- Name: japanese_allowance_level japanese_allowance_level_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.japanese_allowance_level
    ADD CONSTRAINT japanese_allowance_level_pkey PRIMARY KEY (id);


--
-- Name: kpi1_rating kpi1_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kpi1_rating
    ADD CONSTRAINT kpi1_rating_pkey PRIMARY KEY (id);


--
-- Name: leave_balance leave_balance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_balance
    ADD CONSTRAINT leave_balance_pkey PRIMARY KEY (id);


--
-- Name: leave_request leave_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT leave_request_pkey PRIMARY KEY (leave_request_id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: ot_plan_employee ot_plan_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_plan_employee
    ADD CONSTRAINT ot_plan_employee_pkey PRIMARY KEY (id);


--
-- Name: ot_plan ot_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_plan
    ADD CONSTRAINT ot_plan_pkey PRIMARY KEY (id);


--
-- Name: ot_request ot_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_request
    ADD CONSTRAINT ot_request_pkey PRIMARY KEY (ot_request_id);


--
-- Name: payroll payroll_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT payroll_pkey PRIMARY KEY (payroll_id);


--
-- Name: payroll_run payroll_run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll_run
    ADD CONSTRAINT payroll_run_pkey PRIMARY KEY (id);


--
-- Name: pit_bracket pit_bracket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_bracket
    ADD CONSTRAINT pit_bracket_pkey PRIMARY KEY (id);


--
-- Name: pit_config pit_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_config
    ADD CONSTRAINT pit_config_pkey PRIMARY KEY (id);


--
-- Name: benefit pk_benefit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benefit
    ADD CONSTRAINT pk_benefit PRIMARY KEY (benefit_rank);


--
-- Name: public_holiday public_holiday_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_holiday
    ADD CONSTRAINT public_holiday_pkey PRIMARY KEY (id);


--
-- Name: salary_grade_config salary_grade_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade_config
    ADD CONSTRAINT salary_grade_config_pkey PRIMARY KEY (id);


--
-- Name: salary_grade salary_grade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade
    ADD CONSTRAINT salary_grade_pkey PRIMARY KEY (id);


--
-- Name: salary_grade_step salary_grade_step_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade_step
    ADD CONSTRAINT salary_grade_step_pkey PRIMARY KEY (id);


--
-- Name: system_config system_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_config
    ADD CONSTRAINT system_config_pkey PRIMARY KEY (id);


--
-- Name: tax_dependent tax_dependent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_dependent
    ADD CONSTRAINT tax_dependent_pkey PRIMARY KEY (id);


--
-- Name: timesheet timesheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet
    ADD CONSTRAINT timesheet_pkey PRIMARY KEY (id);


--
-- Name: allowance_level uk_allowance_level; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_level
    ADD CONSTRAINT uk_allowance_level UNIQUE (config_id, level_key);


--
-- Name: allowance_rule_value uk_allowance_rule; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_rule_value
    ADD CONSTRAINT uk_allowance_rule UNIQUE (config_id, kind, value);


--
-- Name: attendance uk_attendance_employee_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT uk_attendance_employee_date UNIQUE (employee_id, attendance_date);


--
-- Name: department uk_department_manager; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT uk_department_manager UNIQUE (manager_id);


--
-- Name: employee_info uk_employee_national_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_info
    ADD CONSTRAINT uk_employee_national_id UNIQUE (national_id);


--
-- Name: employee_info uk_employee_si_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_info
    ADD CONSTRAINT uk_employee_si_code UNIQUE (social_insurance_code);


--
-- Name: employee_info uk_employee_tax_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_info
    ADD CONSTRAINT uk_employee_tax_code UNIQUE (tax_code);


--
-- Name: insurance_eligible_contract_type uk_ins_eligible; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insurance_eligible_contract_type
    ADD CONSTRAINT uk_ins_eligible UNIQUE (config_id, contract_type);


--
-- Name: japanese_allowance_level uk_jp_allowance_level; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.japanese_allowance_level
    ADD CONSTRAINT uk_jp_allowance_level UNIQUE (config_id, jlpt_level);


--
-- Name: kpi1_rating uk_kpi1_employee_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kpi1_rating
    ADD CONSTRAINT uk_kpi1_employee_period UNIQUE (employee_id, kpi_year, kpi_month);


--
-- Name: leave_balance uk_leave_balance_employee_year_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_balance
    ADD CONSTRAINT uk_leave_balance_employee_year_type UNIQUE (employee_id, leave_year, leave_type);


--
-- Name: ot_plan_employee uk_ot_plan_employee; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_plan_employee
    ADD CONSTRAINT uk_ot_plan_employee UNIQUE (ot_plan_id, employee_id);


--
-- Name: payroll uk_payroll_employee_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT uk_payroll_employee_period UNIQUE (employee_id, payroll_year, payroll_month);


--
-- Name: payroll_run uk_payroll_run_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll_run
    ADD CONSTRAINT uk_payroll_run_period UNIQUE (run_year, run_month);


--
-- Name: attendance_period_close uk_period_close_year_month; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_period_close
    ADD CONSTRAINT uk_period_close_year_month UNIQUE (close_year, close_month);


--
-- Name: pit_bracket uk_pit_bracket_seq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_bracket
    ADD CONSTRAINT uk_pit_bracket_seq UNIQUE (config_id, seq);


--
-- Name: salary_grade uk_salary_grade_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade
    ADD CONSTRAINT uk_salary_grade_code UNIQUE (config_id, grade_code);


--
-- Name: salary_grade_step uk_salary_grade_step; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade_step
    ADD CONSTRAINT uk_salary_grade_step UNIQUE (grade_id, step_no);


--
-- Name: timesheet uk_timesheet_employee_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet
    ADD CONSTRAINT uk_timesheet_employee_period UNIQUE (employee_id, ts_year, ts_month);


--
-- Name: user_account uk_user_account_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT uk_user_account_username UNIQUE (username);


--
-- Name: work_day uk_workday_employee_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_day
    ADD CONSTRAINT uk_workday_employee_date UNIQUE (employee_id, work_date);


--
-- Name: user_account user_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT user_account_pkey PRIMARY KEY (employee_id);


--
-- Name: work_day work_day_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_day
    ADD CONSTRAINT work_day_pkey PRIMARY KEY (id);


--
-- Name: idx_allowance_config_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_allowance_config_lookup ON public.allowance_config USING btree (status, effective_from);


--
-- Name: idx_api_key_device; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_key_device ON public.api_key USING btree (device_id);


--
-- Name: idx_api_key_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_key_hash ON public.api_key USING btree (key_hash) WHERE (active = true);


--
-- Name: idx_attadj_employee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attadj_employee ON public.attendance_adjustment USING btree (employee_id);


--
-- Name: idx_attadj_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attadj_status ON public.attendance_adjustment USING btree (status);


--
-- Name: idx_contract_employee_current; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contract_employee_current ON public.contract USING btree (employee_id, current_contract);


--
-- Name: idx_insurance_config_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_insurance_config_lookup ON public.insurance_config USING btree (status, effective_from);


--
-- Name: idx_kpi1_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kpi1_period ON public.kpi1_rating USING btree (kpi_year, kpi_month);


--
-- Name: idx_leave_balance_employee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_leave_balance_employee ON public.leave_balance USING btree (employee_id, leave_year);


--
-- Name: idx_notification_employee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_employee ON public.notification USING btree (employee_id, read_flag);


--
-- Name: idx_ope_employee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ope_employee ON public.ot_plan_employee USING btree (employee_id);


--
-- Name: idx_ope_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ope_plan ON public.ot_plan_employee USING btree (ot_plan_id);


--
-- Name: idx_ot_plan_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ot_plan_date ON public.ot_plan USING btree (ot_date);


--
-- Name: idx_ot_plan_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ot_plan_status ON public.ot_plan USING btree (status);


--
-- Name: idx_payroll_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payroll_run_id ON public.payroll USING btree (payroll_run_id);


--
-- Name: idx_pit_config_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pit_config_lookup ON public.pit_config USING btree (status, effective_from);


--
-- Name: idx_public_holiday_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_public_holiday_date ON public.public_holiday USING btree (holiday_date);


--
-- Name: idx_public_holiday_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_public_holiday_year ON public.public_holiday USING btree (holiday_year);


--
-- Name: idx_salary_grade_config_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_salary_grade_config_lookup ON public.salary_grade_config USING btree (status, effective_from);


--
-- Name: idx_syscfg_type_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_syscfg_type_active ON public.system_config USING btree (config_type, active);


--
-- Name: idx_syscfg_type_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_syscfg_type_version ON public.system_config USING btree (config_type, version);


--
-- Name: idx_tax_dependent_employee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tax_dependent_employee ON public.tax_dependent USING btree (employee_id);


--
-- Name: idx_timesheet_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_timesheet_period ON public.timesheet USING btree (ts_year, ts_month);


--
-- Name: idx_workday_date_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workday_date_source ON public.work_day USING btree (work_date, source);


--
-- Name: idx_workday_employee_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workday_employee_date ON public.work_day USING btree (employee_id, work_date);


--
-- Name: idx_workday_locked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workday_locked ON public.work_day USING btree (locked, work_date);


--
-- Name: uk_allowance_published_eff; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_allowance_published_eff ON public.allowance_config USING btree (effective_from) WHERE ((status)::text = 'PUBLISHED'::text);


--
-- Name: uk_insurance_published_eff; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_insurance_published_eff ON public.insurance_config USING btree (effective_from) WHERE ((status)::text = 'PUBLISHED'::text);


--
-- Name: uk_pit_published_eff; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_pit_published_eff ON public.pit_config USING btree (effective_from) WHERE ((status)::text = 'PUBLISHED'::text);


--
-- Name: uk_salary_grade_published_eff; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_salary_grade_published_eff ON public.salary_grade_config USING btree (effective_from) WHERE ((status)::text = 'PUBLISHED'::text);


--
-- Name: allowance_level fk_allowance_level_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_level
    ADD CONSTRAINT fk_allowance_level_config FOREIGN KEY (config_id) REFERENCES public.allowance_config(id) ON DELETE CASCADE;


--
-- Name: allowance_rule_value fk_allowance_rule_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.allowance_rule_value
    ADD CONSTRAINT fk_allowance_rule_config FOREIGN KEY (config_id) REFERENCES public.allowance_config(id) ON DELETE CASCADE;


--
-- Name: api_key fk_api_key_device; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key
    ADD CONSTRAINT fk_api_key_device FOREIGN KEY (device_id) REFERENCES public.device(device_id) ON DELETE CASCADE;


--
-- Name: attendance_adjustment fk_attadj_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_adjustment
    ADD CONSTRAINT fk_attadj_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: attendance fk_attendance_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: check_in_log fk_checkin_log_device; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.check_in_log
    ADD CONSTRAINT fk_checkin_log_device FOREIGN KEY (device_id) REFERENCES public.device(device_id);


--
-- Name: check_in_log fk_checkin_log_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.check_in_log
    ADD CONSTRAINT fk_checkin_log_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: contract fk_contract_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_contract_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: department fk_department_manager; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_manager FOREIGN KEY (manager_id) REFERENCES public.employee_info(employee_id);


--
-- Name: department fk_department_parent; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_parent FOREIGN KEY (parent_id) REFERENCES public.department(department_id);


--
-- Name: employee_info fk_employee_department; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_info
    ADD CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES public.department(department_id);


--
-- Name: insurance_eligible_contract_type fk_ins_eligible_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.insurance_eligible_contract_type
    ADD CONSTRAINT fk_ins_eligible_config FOREIGN KEY (config_id) REFERENCES public.insurance_config(id) ON DELETE CASCADE;


--
-- Name: japanese_allowance_level fk_jp_allowance_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.japanese_allowance_level
    ADD CONSTRAINT fk_jp_allowance_config FOREIGN KEY (config_id) REFERENCES public.allowance_config(id) ON DELETE CASCADE;


--
-- Name: kpi1_rating fk_kpi1_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kpi1_rating
    ADD CONSTRAINT fk_kpi1_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: leave_balance fk_leave_balance_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_balance
    ADD CONSTRAINT fk_leave_balance_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: leave_request fk_leave_request_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT fk_leave_request_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: notification fk_notification_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk_notification_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: ot_plan_employee fk_ope_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_plan_employee
    ADD CONSTRAINT fk_ope_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: ot_plan_employee fk_ope_plan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_plan_employee
    ADD CONSTRAINT fk_ope_plan FOREIGN KEY (ot_plan_id) REFERENCES public.ot_plan(id) ON DELETE CASCADE;


--
-- Name: ot_request fk_ot_request_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_request
    ADD CONSTRAINT fk_ot_request_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: ot_request fk_ot_request_plan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ot_request
    ADD CONSTRAINT fk_ot_request_plan FOREIGN KEY (ot_plan_id) REFERENCES public.ot_plan(id) ON DELETE SET NULL;


--
-- Name: payroll fk_payroll_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT fk_payroll_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: pit_bracket fk_pit_bracket_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pit_bracket
    ADD CONSTRAINT fk_pit_bracket_config FOREIGN KEY (config_id) REFERENCES public.pit_config(id) ON DELETE CASCADE;


--
-- Name: salary_grade fk_salary_grade_config; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade
    ADD CONSTRAINT fk_salary_grade_config FOREIGN KEY (config_id) REFERENCES public.salary_grade_config(id) ON DELETE CASCADE;


--
-- Name: salary_grade_step fk_salary_grade_step_grade; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salary_grade_step
    ADD CONSTRAINT fk_salary_grade_step_grade FOREIGN KEY (grade_id) REFERENCES public.salary_grade(id) ON DELETE CASCADE;


--
-- Name: tax_dependent fk_tax_dependent_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_dependent
    ADD CONSTRAINT fk_tax_dependent_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: timesheet fk_timesheet_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet
    ADD CONSTRAINT fk_timesheet_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- Name: user_account fk_user_account_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT fk_user_account_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id);


--
-- Name: work_day fk_workday_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_day
    ADD CONSTRAINT fk_workday_employee FOREIGN KEY (employee_id) REFERENCES public.employee_info(employee_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict Zn9Xc2ZT0TBvW4y8MRgfxMroDjkivJQt21lejUh9c6goKvdbpevr3BIgnoMWg3i

